# Generated by Django 3.0.7 on 2023-09-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

        dependencies = [
                        ('pages', '0004_auto_20230902_2207'),
                            ]

            operations = [
                            migrations.RenameField(
                                            model_name='team',
                                                        old_name='created_data',
                                                                    new_name='created_date',
                                                                            ),
                                ]
