# Generated by Django 3.0.7 on 2023-09-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

        dependencies = [
                        ('pages', '0003_team_linkedin_link'),
                            ]

            operations = [
                            migrations.RenameField(
                                            model_name='team',
                                                        old_name='desigantion',
                                                                    new_name='designation',
                                                                            ),
                                ]
